<?php
// =====================
// statements_pdf.php
// =====================

// Enable error reporting for debugging
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require('fpdf/fpdf.php');

// ---------------------
// Session & Authentication
// ---------------------
session_start();
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

// ---------------------
// Database Connection
// ---------------------
$conn = new mysqli("localhost", "root", "", "billsimp_db");
if ($conn->connect_error) die("Connection failed: " . $conn->connect_error);

$user_id = intval($_SESSION['user_id']);

// ---------------------
// Determine PDF Type
// ---------------------
$fullPDF = isset($_GET['all']);             // Full PDF of all statements
$statement_id = isset($_GET['statement_id']) ? intval($_GET['statement_id']) : 0;

// ---------------------
// Fetch Data
// ---------------------
if ($fullPDF) {
    $sql = "SELECT * FROM statements WHERE user_id = $user_id ORDER BY date DESC";
    $result = $conn->query($sql);
    if ($result->num_rows == 0) die("No statements found.");
} else {
    $sql = "SELECT * FROM statements WHERE id = $statement_id AND user_id = $user_id";
    $result = $conn->query($sql);
    if ($result->num_rows == 0) die("Statement not found.");
    $row = $result->fetch_assoc();
}

// ---------------------
// PDF Generation
// ---------------------
$pdf = new FPDF();
$pdf->AddPage();

// Optional: add header function
function pdfHeader($pdf, $title = "Statements") {
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->Cell(0, 10, $title, 0, 1, 'C');
    $pdf->Ln(5);
}

// Optional: add footer function
function pdfFooter($pdf) {
    $pdf->SetY(-15);
    $pdf->SetFont('Arial', 'I', 8);
    $pdf->Cell(0, 10, 'Generated by BillSimp', 0, 0, 'C');
}

// ---------------------
// Generate PDF Content
// ---------------------
if ($fullPDF) {
    pdfHeader($pdf, "All Statements");

    // Table Header
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->Cell(40, 10, 'Date', 1);
    $pdf->Cell(70, 10, 'Description', 1);
    $pdf->Cell(40, 10, 'Amount', 1);
    $pdf->Cell(40, 10, 'Balance', 1);
    $pdf->Ln();

    // Table Body
    $pdf->SetFont('Arial', '', 12);
    while ($row = $result->fetch_assoc()) {
        $pdf->Cell(40, 10, $row['date'], 1);
        $pdf->Cell(70, 10, $row['description'], 1);
        $pdf->Cell(40, 10, number_format($row['amount'], 2), 1);
        $pdf->Cell(40, 10, number_format($row['balance'], 2), 1);
        $pdf->Ln();
    }

} else {
    pdfHeader($pdf, "Statement Details");

    $pdf->SetFont('Arial', '', 12);
    $pdf->Cell(50, 10, 'Date:', 0);
    $pdf->Cell(0, 10, $row['date'], 0, 1);

    $pdf->Cell(50, 10, 'Description:', 0);
    $pdf->Cell(0, 10, $row['description'], 0, 1);

    $pdf->Cell(50, 10, 'Amount:', 0);
    $pdf->Cell(0, 10, number_format($row['amount'], 2), 0, 1);

    $pdf->Cell(50, 10, 'Balance:', 0);
    $pdf->Cell(0, 10, number_format($row['balance'], 2), 0, 1);
}

// Optional footer
pdfFooter($pdf);

// ---------------------
// Output PDF
// ---------------------
$filename = $fullPDF ? "all_statements.pdf" : "statement_" . $row['id'] . ".pdf";
$pdf->Output('I', $filename);
exit();

